// Import necessary Redux and redux-persist dependencies
import { createSlice } from '@reduxjs/toolkit';
import { combineReducers } from 'redux';

// Define the initial state for course ID
const initialCourseState = { value: null }
 
// Create a course ID slice
export const course = createSlice({
  name: 'course',
  initialState: initialCourseState,
  reducers: {
    // Action to set the course ID
    setCourse: (state, action) => {
      state.value = action.payload;
    },
    // Action to clear the course ID if needed
    clearCourse: (state) => {
      state.value = null;
    },
    // You can add more actions for course ID state management here
  },
});

// Export action creators generated by the course ID slice
export const { setCourse, clearCourse } = course.actions;

// Define the initial state for courses
const initialCoursesState = { value: [] }

// Create a courses slice
export const courses = createSlice({
  name: 'courses',
  initialState: initialCoursesState,
  reducers: {
    // Action to set the courses
    setMyCourses: (state, action) => {
      state.value= action.payload;
    },
    // Action to clear the courses if needed
    clearCourses: (state) => {
      state.value = []; // Clear the courses by setting it to an empty array
    },
  },
});

// Export action creators generated by the courses slice
export const { setMyCourses, clearCourses } = courses.actions;

// Define the initial state for the token
const initialTokenState = { value: {} }

// Create a token slice
export const token = createSlice({
  name: 'token',
  initialState: initialTokenState,
  reducers: {
    // Action to set the token when a user enters it
    setToken: (state, action) => {
      
      state.value = action.payload;
      localStorage.setItem("token", state.value);
      
    },
    // Action to clear the token if needed
    clearToken: (state) => {
      state.value = null;
      localStorage.removeItem("token");
    },
  },
});

// Export action creators generated by the token slice
export const { setToken, clearToken } = token.actions;


// const initialDomainState = {value: "https://client.canvas-hub.com:3000/"}
const initialDomainState = {value: "http://localhost:49152/"}

// Create a token slice
export const domain = createSlice({
  name: 'domain',
  initialState: initialDomainState,
  reducers: {
    // Action to set the domain when a user enters it
    setDomain: (state, action) => {
      state.value = action.payload;
    },
    // Action to clear the domain if needed
    clearDomain: (state) => {
      state.value = null;
    },
  },
});

// Export action creators generated by the token slice
export const { setDomain, clearDomain } = domain.actions;

// Combine all reducers into a single rootReducer
export const rootReducer = combineReducers({
  course: course.reducer,
  token: token.reducer,
  courses: courses.reducer,
  domain: domain.reducer
});