import { createSlice } from '@reduxjs/toolkit';

// Define the initial state for course ID
const initialCourseState = {
  courseID: null,
};

// Create a course ID slice
export const courseIDReducer = createSlice({
  name: 'courseID',
  initialState: initialCourseState,
  reducers: {
    // Action to set the course ID
    setCourseID: (state, action) => {
      state.courseID = action.payload;
    },
    // Action to clear the course ID if needed
    clearCourseID: (state) => {
      state.courseID = null;
    },
    // You can add more actions for course ID state management here
  },
});

// Export action creators generated by the course ID slice
export const { setCourseID, clearCourseID } = courseIDReducer.actions;

// Export the reducer for the course ID slice
export default courseIDReducer.reducer;