on:
    push:
      branches:
        - dev
jobs:
    build_frontend:
      name: Build Frontend
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v3
          with:
            node-version: '12'
            cache: 'npm'

        - name: Install SSH Keys
          run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
        - name: Build Frontend
          run: |
            cd client
            npm install
            npm run build
  
    build_backend:
      name: Build Backend
      runs-on: ubuntu-latest
      steps:
        - name: Install SSH Keys
          run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
        - name: Update Application Code (Server)
          run: |
            ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && \
            git pull origin ${{ secrets.PROD_BRANCH }}"
        - name: Install Backend Dependencies
          run: |
            ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }}/server && \
            npm install" 

    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        needs: [build_frontend, build_backend]
        steps:
        - uses: actions/checkout@v4
        - name: Install SSH Keys
          run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
        - name: Deploy Backend
          run: |
            ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && \
            pm2 reload index"

        - name: Deploy Frontend
          run: |
            cd client
            scp ./build/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/client.canvas-hub.com/
          
  

 