on:
    push:
      branches:
        - dev
jobs:
    build_frontend:
      name: Build Frontend
      runs-on: ubuntu-latest
      steps:
        - name: Install SSH Keys
          run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
        - name: Build Frontend
          run: |
            ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }}/client && \
            npm install && \
            npm run build"
  
    deploy_backend:
      name: Deploy Backend
      runs-on: ubuntu-latest
      steps:
        - name: Install SSH Keys
          run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
        - name: Update Application Code (Server)
          run: |
            ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && \
            git pull origin ${{ secrets.PROD_BRANCH }}"
        - name: Install Backend Dependencies
          run: |
            ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }}/server && \
            npm install"
        - name: Reload Backend Server
          run: |
            ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && \
            pm2 reload index"
  
    deploy_frontend:
      name: Deploy Frontend
      runs-on: ubuntu-latest
      needs: [build_frontend, deploy_backend]
      steps:
        - name: Deploy Frontend
          run: |
            ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }}/client && \
            sudo cp -r ./build/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/client.canvas-hub.com/html"
  
    cleanup:
      name: Remove key
      needs: [deploy_frontend]
      runs-on: ubuntu-latest
      steps:
        - name: Remove SSH key
          run: rm -rf ~/.ssh
  